###Directory Address /home/vireogod/prometheus_install/prometheus/prometheus.yml ~/prometheus_export.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'linux'
    static_configs:
      - targets: ['192.168.1.2xx:9100']  # Linux no>

  - job_name: 'windows'
  - job_name: 'windows'
    static_configs:
      - targets: ['192.168.1.2xx:9182']  # Windows >

  - job_name: 'baremetal1'
    static_configs:
      - targets: ['192.168.1.2xx:9100']  # Only if >

  - job_name: 'baremetal2'
    static_configs:
      - targets: ['192.168.1.2xx:9100']  # Only if
      - job_name: 'router'
    static_configs:
      - targets: ['192.168.1.x:9100']    # Only if >
